import {
  IDENTIFIER,
  // REGEX
  FUNCTION_IDENTIFIER
} from '../../../constants';

const convertName2 = (name) => `${name.toLowerCase().replace(/ /g, '_').replace(/[ .,"'? +=-]/g, '')}`;
const setValues = (formValues, callback, name) => {
  callback(formValues[name] ?? '');
};
export const CustomerReadOnlyFields = [
  {
    label: 'Customer Information',
    data: [
      {
        name: convertName2('Customer Name'),
        label: 'Customer Name',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Customer Name')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Customer ID'),
        label: 'Customer ID',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Customer ID')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('DOB'),
        label: 'DOB',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('DOB')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Primary Mobile No.'),
        label: 'Primary Mobile No.',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Primary Mobile No.')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('PAN Number'),
        label: 'PAN Number',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('PAN Number')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
    ]
  },
  {
    label: 'Client Details',
    data: [
      {
        name: convertName2('Branch Code'),
        label: 'Branch Code',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Branch Code')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
    ]
  },
  {
    label: 'KYC Details',
    data: [
      {
        name: convertName2('CKYC'),
        label: 'CKYC',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('CKYC')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Aadhaar Number'),
        label: 'Aadhaar Number',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Aadhaar Number')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Customer Name'),
        label: 'Customer Name',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Customer Name')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Father Name'),
        label: 'Father Name',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Father Name')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('DOB'),
        label: 'DOB',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('DOB')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Address 1'),
        label: 'Address 1',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Address 1')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Address 2'),
        label: 'Address 2',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Address 2')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Pincode'),
        label: 'Pincode',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Pincode')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('City'),
        label: 'City',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('City')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('State'),
        label: 'State',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('State')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('PAN Number'),
        label: 'PAN Number',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('PAN Number')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('PAN Customer Name'),
        label: 'PAN Customer Name',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('PAN Customer Name')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Upload Form 60'),
        label: 'Upload Form 60',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Upload Form 60')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('ID Proof'),
        label: 'ID Proof',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('ID Proof')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('ID Proof Upload'),
        label: 'ID Proof Upload',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('ID Proof Upload')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('ID Proof Number'),
        label: 'ID Proof Number',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('ID Proof Number')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('ID Proof Remarks'),
        label: 'ID Proof Remarks',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('ID Proof Remarks')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('ID Proof Expiry Date'),
        label: 'ID Proof Expiry Date',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('ID Proof Expiry Date')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('ID Proof OSV Done'),
        label: 'ID Proof OSV Done',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('ID Proof OSV Done')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Address Proof'),
        label: 'Address Proof',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Address Proof')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Address Proof Upload'),
        label: 'Address Proof Upload',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Address Proof Upload')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Address Proof Number'),
        label: 'Address Proof Number',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Address Proof Number')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Address Proof Remarks'),
        label: 'Address Proof Remarks',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Address Proof Remarks')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Address Proof Expiry Date'),
        label: 'Address Proof Expiry Date',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Address Proof Expiry Date')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Address Proof OSV Done'),
        label: 'Address Proof OSV Done',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Address Proof OSV Done')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Risk Category'),
        label: 'Risk Category',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Risk Category')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
    ]
  },
  {
    label: 'Personal Information',
    data: [
      {
        name: convertName2('Number of Years in Current Residence'),
        label: 'Number of Years in Current Residence',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Number of Years in Current Residence')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Education'),
        label: 'Education',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Education')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Primary Mobile Number'),
        label: 'Primary Mobile Number',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Primary Mobile Number')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Secondary Mobile Number'),
        label: 'Secondary Mobile Number',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Secondary Mobile Number')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Email id'),
        label: 'Email id',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Email id')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Marital Status'),
        label: 'Marital Status',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Marital Status')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Gender'),
        label: 'Gender',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Gender')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
    ]
  },
  {
    label: 'Employment Information',
    data: [
      {
        name: convertName2('Customer Occupation'),
        label: 'Customer Occupation',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Customer Occupation')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Annual Income'),
        label: 'Annual Income',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Annual Income')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('PSL Status'),
        label: 'PSL Status',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('PSL Status')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('PSL Category'),
        label: 'PSL Category',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('PSL Category')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
    ]
  },
  {
    label: 'Occupation Address',
    data: [
      {
        name: convertName2('Address'),
        label: 'Address',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Address')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Area_Locality'),
        label: 'Area/Locality',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Area_Locality')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Landmark'),
        label: 'Landmark',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Landmark')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Pincode'),
        label: 'Pincode',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Pincode')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('City'),
        label: 'City',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('City')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('State'),
        label: 'State',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('State')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
    ]
  },
  {
    label: 'Customer & Nominee Details',
    data: [
      {
        name: convertName2('Customer Live Photo Upload'),
        label: 'Customer Live Photo Upload',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Customer Live Photo Upload')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Gold Nominee 1 Relationship'),
        label: 'Gold Nominee 1 Relationship',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Gold Nominee 1 Relationship')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Other Relation'),
        label: 'Other Relation',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Other Relation')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Nominee 1 Name'),
        label: 'Nominee 1 Name',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Nominee 1 Name')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Nominee 1 DOB'),
        label: 'Nominee 1 DOB',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Nominee 1 DOB')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Nominee 1 Mobile Number'),
        label: 'Nominee 1 Mobile Number',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Nominee 1 Mobile Number')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Gold Nominee 2 Relationship'),
        label: 'Gold Nominee 1 Relationship',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Gold Nominee 1 Relationship')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Other Relation2'),
        label: 'Other Relation',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Other Relation2')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Nominee 2 Name'),
        label: 'Nominee 2 Name',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Nominee 2 Name')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Nominee 2 DOB'),
        label: 'Nominee 2 DOB',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Nominee 2 DOB')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Nominee 2 Mobile Number'),
        label: 'Nominee 2 Mobile Number',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Nominee 2 Mobile Number')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
    ]
  },
  {
    label: 'Relationship Manager',
    data: [
      {
        name: convertName2('Sourcing Person Name'),
        label: 'Sourcing Person Name',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Sourcing Person Name')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Sourcing Person Email ID'),
        label: 'Sourcing Person Email ID',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Sourcing Person Email ID')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Sourcing Person Mobile No'),
        label: 'Sourcing Person Mobile No.',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Sourcing Person Mobile No')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
    ]
  },
  {
    label: 'Bank Details',
    data: [
      {
        name: convertName2('Account Number'),
        label: 'Account Number',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Account Number')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('IFSC Code'),
        label: 'IFSC Code',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('IFSC Code')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Bank Name'),
        label: 'Bank Name',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Bank Name')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Branch Name'),
        label: 'Branch Name',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Branch Name')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Verification Status'),
        label: 'Verification Status',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Verification Status')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Beneficiary Name'),
        label: 'Beneficiary Name',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Beneficiary Name')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Upload Cheque_Passbook'),
        label: 'Upload Cheque/Passbook',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Upload Cheque_Passbook')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
      {
        name: convertName2('Bank OSV Done'),
        label: 'Bank OSV Done',
        type: 'text',
        identifier: IDENTIFIER.INPUTTEXT,
        disabled: true,
        defaultValue: 'test',
        customFunction: (formValues, callback) => setValues(formValues, callback, convertName2('Bank OSV Done')),
        functionMethod: FUNCTION_IDENTIFIER.ON_INIT,
      },
    ]
  },
];
