export const REGEX = {
  NUMBER: /^[0-9]+$/i,
  ALPHABETS: /^[A-Za-z\s]+$/i,
  ALPHANUMERIC: /^[A-Za-z0-9\s]+$/i,
  PASSWORD: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*_=+-]).{8,12}$/i,
  EMAIL: /^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$/i,
  AADHAAR: /^[2-9]{1}[0-9]{3}[0-9]{4}[0-9]{4}$/i,
  PANCARD: /[A-Z]{3}[P]{1}[A-Z]{1}[0-9]{4}[A-Z]{1}$/i,
  OTPVERIFICATION: /^[0-9]{1,10}$/i,
  PINCODE: /^[0-9]{6}$/i,
  MOBILENUMBER: process.env.REACT_APP_ENVIRONMENT === 'prod' ? /^(6|7|8|9)+[0-9]{9}$/i : /^(1|2|3|4|5|6|7|8|9)+[0-9]{9}$/i,
  MOBILE: /^[0-9]{10}$/i,
  TWODIGITDECIMAL: /^(?:\d*\.\d{1,2}|\d+)$/,
  CKYC: /^(?!\s)(?![\s\S]*\s$)[a-zA-Z0-9]+$/i,
  ADDRESS: /^[A-Za-z0-9\s/]+$/i,
  ALPHABETSTRIMSPACE: /^(?!\s)(?![\s\S]*\s$)[a-zA-Z]+$/i,
  ALPHANUMERICTRIMSPACE: /^(?!\s)(?![\s\S]*\s$)[a-zA-Z0-9]+$/i,
  ALPHABETSTRIMSPACESTARTEND: /^(?!\s)(?![\s\S]*\s$)[a-zA-Z\s]+$/i,
  ALPHABETSHYPHENTRIMSPACESTARTEND: /^(?!\s)(?![\s\S]*\s$)[a-zA-Z-\s]+$/i,
  ALPHANUMERICTRIMSPACESTARTEND: /^(?!\s)(?![\s\S]*\s$)[a-zA-Z0-9\s]+$/i,
  SPACESTARTEND: /^(?! ).*[^ ]$/i,
  AMOUNT: /^[0-9,]+$/i,
  GOLDPOUCHNUMBER: /^[G]{1}[L]{1}[B]{1}[S,M,L]{1}[0-9]{7}$/,
  ONLYCHARANDDIGITS: /^(?=.*[a-zA-Z -])(?=.*\d)[a-zA-Z\d -]+$/i,
  GSTNUMBER: /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/,
  SHIVALIKGOLDPOUCHNUMBER: /^[S]{1}[S]{1}[F]{1}[B]{1}[S,L]{1}[0-9]{5}$/,
  UDYAMNUMBER: /^[U]{1}[D]{1}[Y]{1}[A]{1}[M]{1}[-]{1}[A-Z]{2}[-]{1}[0-9]{2}[-]{1}[0-9]{7}$/,
  CGCLUSER: /^CGCL|cgcl\d+$/,
  ALPHANUMBERICWITHTWOMANDATORYLETTERS: /^[a-zA-Z0-9]*(?:[a-zA-Z][a-zA-Z0-9]*){2,}$/,
  MUSTALPHANUMBERIC: /^(?=.*[a-zA-Z])(?=.*\d)[a-zA-Z\d]+$/i,
  UPI: /^[\w.-]+@[\w.-]+$/
};
